### PR TITLE
Gentoo compat

### PR DESCRIPTION
**Pull request by mgomersbach**
The specials/block syntax allow me to support Gentoo/Portage.

### CODE REVIEW

**Comment by mgomersbach** [comment]
Should I comment this PR more, or should I delete it, convert the formula to yaml dataholders first (os_family <- os <- osfinger), and then add Gentoo support?

**Comment by javierbertoli** [comment]
@mgomersbach tbh, I'd love to see the formula converted to yaml dataholders (and, if possible, getting rid of these 'ng' things). But otoh, you added a full distro support following current structure, so I'd say we merge this PR and then we can submit some other PRs to move to yaml.

All that said, I don't have a Gentoo distro around, so I can't say if this PR is OK (I mean os-aware, code lgtm), sorry. If nobody can take a look at it in a couple of days, I'll merge it as is.

My 2c.

**Comment by javierbertoli** [comment]
As promised, a couple of days passed :smile:
Thanks, @mgomersbach!

**Comment by mgomersbach** [comment]
Thank you! Feels good to delete local branches and use upstream 8)

**Pull request merged**
