### PR TITLE
Add example to use a specific php version when using multiple ones

### PR DESCRIPTION
**Pull request by Yoda-BZH**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Related to #167 ( [php/ng] support the use of a list of php versions)

### Describe the changes you're proposing

Add an example on how to use a specific php version in a fpm pool when using multiple versions

### Pillar / config required to test the proposed changes

None.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@Yoda-BZH Thanks for the contribution.

@arthurlogilab Can you confirm that this is how `phpversion` should be set in the pillar, after your PR (#167)?

**Comment by myii** [comment]
@Yoda-BZH It would be helpful if you can modify your commit message according the [contributing guidelines](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#commit-message-formatting).  Please amend the commit and then force push it.

If it's too much trouble, the commit message can be fixed during the merge.

**Comment by arthurlogilab** [comment]
@myii the contribution by @Yoda-BZH is to signify that the phpversion can also be specified for a given php-fpm pool. A quick look at the code makes me think this should work, I wouldn't be so sure with a list there. I don't think there's a need to though.

**Comment by myii** [comment]
@Yoda-BZH Merged, thanks again for the clarification.  I've modified the commit message upon merge.

Appreciate the review, @arthurlogilab.

**Comment by Yoda-BZH** [comment]
Ho, I planned on modifying the commit message today, sorry for the delay.

Thank you for the merge.

**Pull request merged**
