### PR TITLE
add php version to redis for debian in map.jinja

### PR DESCRIPTION
**Pull request by Ahummeling**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Set the php version in the map for debian module redis, make it install `php8.0-redis` since `php-redis` results in 7.3 on server and 8.0 on another server. I am not aware for the initial reason for not including the php version.

### Debug log showing how the proposed changes work

```
----------
          ID: php_install_redis
    Function: pkg.installed
        Name: redis
      Result: True
     Comment: The following packages were installed/updated: php8.0-redis
     Started: 16:11:02.328496
    Duration: 3485.581 ms
     Changes:   
              ----------
              php-redis:
                  ----------
                  new:
                      5.3.4+4.3.0-1+0~20210329.35+debian10~1.gbpdc7ead
                  old:
                      5.3.1+4.3.0-1+0~20200708.25+debian10~1.gbp800f71
              php8.0-redis:
                  ----------
                  new:
                      5.3.4+4.3.0-1+0~20210329.35+debian10~1.gbpdc7ead
                  old:
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

I'm sorry if this PR seems half assed. I'm a total noob when it comes to salt, feel free to close the PR if it doesn't meet the standards.

### CODE REVIEW

**Comment by johnkeates** [comment]
It seems the commitlint is not happy with the way the commit is named; if you check https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst you'll find the commit message formatting notes and that should clear this up. 

I have started the CI anyway to validate the code change as-is, but before this can be merged the commit message should probably be updated.

**Comment by Ahummeling** [comment]
Right, I've squashed my commits and wrote a clean commit message. Also updated the testcases that broke as a result of the change.

**Comment by myii** [comment]
Apologies for the delay, @Ahummeling.  The failing tests should be simple enough to resolve.  Just want to confirm that @sticky-note is happy with the implementation.

**Comment by Ahummeling** [comment]
Apologies for the seemingly strange commits / pushes all over. I'm having a ton of difficulty figuring out the github webui. I'm used to using gitlab. I don't think I should've pressed that fetch upstream button, it did not do what I thought it did. The changelist is now showing a ton of changes that come from squashing the commits incorrectly. I'll see if I can resolve those, so a review can be done correctly.

**Comment by Ahummeling** [comment]
Seems like the tests are passing again, at least the ones that could be triggered without approval.
If anything needs to happen still, I will pick it up asap

**Comment by myii** [comment]
> Apologies for the seemingly strange commits / pushes all over. I'm having a ton of difficulty figuring out the github webui. I'm used to using gitlab. I don't think I should've pressed that fetch upstream button, it did not do what I thought it did. The changelist is now showing a ton of changes that come from squashing the commits incorrectly. I'll see if I can resolve those, so a review can be done correctly.

@Ahummeling Not to worry, we can always rebase this PR to make things cleaner.  If you're comfortable doing it at your end, you can rebase your commits and then force push back to this PR's branch.  If not, we're able to do that from the GitHub interface at the time of merging.

**Comment by johnkeates** [comment]
I gave the extra checks a little push so we can see if it works everywhere 👍

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Merged, thanks for the PR @Ahummeling -- and once again, apologies for the delay.
Appreciate the help along the way, @johnkeates.

**Pull request merged**
