### PR TITLE
Added missing settings for ubuntu.

### PR DESCRIPTION
**Pull request by stokbaek**

### CODE REVIEW

**Comment by gravyboat** [comment]
@aboe76 Could you please take a look at this?

**Comment by aboe76** [comment]
@stokbaek, I don't get the change did something not work ?
As fas I could see, it should be using first some ubuntu specific mapping for the packages,
and then because ubuntu also uses os_family debian, reuse those settings and merge it , for the minion...

It looks like your changes, will duplicate all settings ubuntu and debian, am I correct?

**Comment by stokbaek** [comment]
@aboe76 as it will return true to the if statement on line 289 will it never get to a debian section as this is in an else statement to this if statement.

**Comment by aboe76** [comment]
Tested the new map.jinja on our debian machines no problem.
Can somebody check this on ubuntu?

**Comment by aboe76** [comment]
ran a ubuntu xenial vm to test this and it also works without a problem,
merging this.

**Comment by gravyboat** [comment]
Thanks @aboe76.

**Pull request merged**
