### PR TITLE
[WIP] (Re)adding support for RedHat and Debian external repos

### PR DESCRIPTION
**Pull request by sc250024**
## STATUS: PR OPENED, STILL WORKING ON CHANGES

This PR will (re)add support for the Debian DotDeb, and RedHat Webtatic external PHP repositories. It will also clean up the Jinja maps so that the logic is clearer, and most defaults will be stored in YAML files.

### CODE REVIEW

**Comment by sc250024** [comment]
@gravyboat @aboe76 Would you guys mind taking a look at the structure I have? I only modified `php/map.jinja` for now, but will use something similar for the NG version too.

@aboe76 I saw your note about the postgres-formula, I will take a look today.

**Comment by aboe76** [comment]
@sc250024 that's why I pointed you in the postgres-formula direction, it has yaml files per:
- defaults.yaml
- codename : codenamemap.yaml
- os: osmap.yaml
- osmajorrelease: osmajorreleasemap.yaml
- repo: repo.yaml

**Comment by sc250024** [comment]
@aboe76 Are we sure we want to use that kind of structure here as well? I ask because whereas Postgres is one application, this PHP formula has to account for many more variations than the postgres-formula. Is the postgres-formula method now considered standard?

**Comment by aboe76** [comment]
@sc250024 I it is not standard, but I thought, it might be a good direction how to import all the different yaml files.

**Comment by sc250024** [comment]
@aboe76 In that case, I will take that approach. Given the nature of how many packages this formula deals with, I thought having a `defaults.yaml` for non-external repos and `defaults.extrepo.yaml` for external repos might be easier. However, I see the benefit in postgres-formula's approach.

@gravyboat Thoughts?

**Comment by gravyboat** [comment]
Seems fine to me. My only concern is minimal with the use of:
```
pkgrepo:
  - managed
```
Instead of `pkgrepo.managed`.

**Comment by sc250024** [comment]
@aboe76 @gravyboat I'll get those changes pushed out. It's another major overhaul, and I'll do my best to get it out as quick as I can.

**Comment by aboe76** [comment]
@sc250024 thanks for your great work !! :)

**Comment by aboe76** [comment]
@sc250024 I got an idea, maybe it is nothing maybe it could help,
instead of focusing on os / osmajor release between debian/ubuntu / etc.

it should be focused around which repo is used:
dotdeb -> debian specific
ondrej, -> ubuntu ppa or debian repo... but the packages are named the same
Webtatic -> redhat specific
default -> ubuntu and debian (naming should be the same because of the same origin)

maybe this will make some decisions or if statements easier...?

**Comment by sc250024** [comment]
@aboe76 That's essentially what I was trying to go for in the updated file `php/map.jinja`. The logic is essentially:

>     # Is external repo being used?
>       # Load defaults for all OS types, and merge that with OS specific map with PHP version number
>     # Else
>       # Use default package maps based on packages native to that OS
>     # EndIf

Which simplifies the Jinja map greatly since most of the information is contained within either `defaults.extrepo.yaml` or `defaults.yaml`.

Regarding your comment "ubuntu ppa or debian repo... but the packages are named the same" I haven't worked with PHP to such a level to say how similar the PPA repo and DotDeb repo are. I know they use the same naming standard of `phpX.Y-package`, but I don't know if they offer the same package availability.

For example, I know the Ubuntu PPA has versions 5.5, 5.6, 7.0, and 7.1 (which all use the same naming), but I can't say if DotDeb has all those packages available.

**Comment by aboe76** [comment]
@sc250024 not between the two repo's but duty has debian repo too instead of a PPA

**Comment by aboe76** [comment]
@sc250024 have you seen this message:
https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/

Guillaume is pointing at https://deb.sury.org/ for php 7.1 and higher.

**Comment by sc250024** [comment]
@aboe76 Hey, that's helpful! Admittedly I've been a bit swamped with work, but I'll start working on this again. NOT having to distinguish between Debian and Ubuntu anymore lightens the load.

**Comment by sc250024** [comment]
@aboe76 To piggy back on my last comment, looks like https://packages.sury.org/php/dists/ supports `jessie` and `stretch` versions of Debian.

**Comment by aboe76** [comment]
@sc250024 dropping dotdeb isn't an option, if it's possible to switch between the two repo's I think we can cover the backward compatibility issues

**Comment by aboe76** [comment]
@sc250024 how is it going?

I found some more information what could help with the formula:
https://github.com/oerdnj/deb.sury.org/wiki/Managing-Multiple-Versions

**Comment by sc250024** [comment]
@aboe76 That definitely helps when writing an SLS to make sure the correct version is specified. In your opinion, what's the most urgent thing right now needed for this formula? Admittedly this PR was a bit too ambitious (not to say it can't be eventually done; just need to limit the scope a bit for now)

**Comment by aboe76** [comment]
@sc250024, if you want to limit the scope: concentrate on the external repos mapping logic.

**Pull request closed without merging**
