### PR TITLE
Fix Backward compatibility problem

### PR DESCRIPTION
**Pull request by pawelrosada**

### CODE REVIEW

**Comment by sticky-note** [comment]
Thanks, is this variable is intended to use only with RedHat.
Formulas fails in my side because I run it on a Debian server.
After investigation I found this 'enable_php_repo' is only set for RedHat: https://github.com/saltstack-formulas/php-formula/blob/0c923245e67c31bd51b78595bae57ad066c2a31b/php/ng/installed.jinja#L75
As documented on pillar, there is an 'use_external_repo' and 'external_repo_name' vars. What is differnet with yours ?

**Comment by schindlerf** [comment]
Same as Issue #169

**Comment by aboe76** [comment]
@sticky-note can you test the proposed solution

**Comment by sticky-note** [comment]
It seems to work but #166 seems to modify behavior for RedHat only ...

**Comment by ze42** [comment]
It works here too, properly fixes bug introduced by #166 for non-RedHat.

Fix kinda required for non-RedHat use.

**Comment by aboe76** [comment]
merged it.

**Pull request merged**
