### PR TITLE
php.ng.apache2: FreeBSD support

### PR DESCRIPTION
**Pull request by alxwr**
* Configuration of `mod_php`
* Derive `mod_php` version from PHP version
* Integration with _apache-formula_ (with opt-out and entry in `pillar.example`)
* Made module config file path configurable

### CODE REVIEW

**Comment by alxwr** [comment]
I'm extending this PR to support `php.ng.composer` (and its dependencies) on FreeBSD and Ubuntu.

**Comment by alxwr** [comment]
Tested on Ubuntu 16.04 and FreeBSD 10.3.

@aboe76 If your time allows it, would you please test this PR on your systems?

**Comment by aboe76** [comment]
@alxwr php.ng.composer tested and it works ! :+1:

**Comment by alxwr** [comment]
@aboe76 Thank you!
I added a minor bugfix for the composer update. Worked in my tests.

**Pull request merged**
