### PR TITLE
fix(pillar): fix pillar.get still looking under 'ng' namespace

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by myii** [comment]
Excellent catch, @n-rodriguez!  Much needed after #183, thanks.

**Comment by sticky-note** [comment]
@n-rodriguez @myii Extremely sorry that I've not verified that part each time I made a rebase :'(

**Comment by sticky-note** [comment]
Can you amend the v1.0.0 to make that clean ?

**Comment by n-rodriguez** [comment]
> tada This PR is included in version 1.0.1 tada

**Comment by sticky-note** [comment]
Hope that's not a problem to not have a fully functionnal `v1.0.0`

**Comment by myii** [comment]
@sticky-note The first release of a new version always has minor issues with it, it's normal.  You did a great job, especially with the multiple rebases that had to take place!

**Pull request merged**
