### PR TITLE
Add support for Ubuntu Xenial Xerus (16.04). Fixes #97

### LINKED ISSUE #97: Xenial package names has changed from php5 to php.
PHP packages in Ubuntu Xenial Xerus (16.04) has been renamed from php5 to php.

Now it has php-gd, php-cli, etc.

### PR DESCRIPTION
**Pull request by alinefr**
Ubuntu Xenial brings php7.0, but also it brings generic php packages named:
```
php
php-cli
php-gd
php-curl
```
... and so on.

So I've added a conditional in map.jinja (including the ng one) to filter Ubuntu version greater than 16.04. I've tried my best to not break older Ubuntu versions or other OSs.

### CODE REVIEW

**Comment by gravyboat** [comment]
From a quick check this looks fine to me and it seems to be backwards compatible (at least for the basic map.jinja). I'm going to leave this open to see if anyone else wants to weigh in, if they don't within a day or two please ping me and I'll get this merged.

**Comment by babilen** [comment]
Thois branch has conflicts now, a rebase and force push would be great!

**Comment by alinefr** [comment]
Done!

**Comment by gravyboat** [comment]
Taking @babilen's comment as a sign off so I will merge this in. Thanks!

**Comment by aboe76** [comment]
This breaks Archlinux support,

**Comment by aboe76** [comment]
fixed it with #101

**Comment by gravyboat** [comment]
Thanks @aboe76.

**Comment by alinefr** [comment]
Sorry for that. Glad you already fixed it.

**Pull request merged**
