### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by aboe76** [comment]
@n-rodriguez the only thing to fix the checks, is to use semantic release in your commit message:
see: https://github.com/saltstack-formulas/php-formula/blob/master/docs/CONTRIBUTING.rst#commit-message-formatting

**Comment by myii** [comment]
@aboe76 It's actual tripping up on `yamllint`, due to the Jinja inside the test pillar.  @n-rodriguez is a seasoned `semantic-release` expert, there's never any mistakes there!

In any case, I've just been testing out another couple of commits to get around this `yamllint` issue (by introducing a specific suite for `ubuntu`) -- are you OK if I add this on to this PR, @n-rodriguez?  Great PR, by the way.

**Comment by aboe76** [comment]
@n-rodriguez and @myii excuse my ingnorance...

**Comment by myii** [comment]
@aboe76 No problem, it's because the `lint` stage now does both checks (`commitlint` and `yamllint`).  The errors can be seen here:

* https://travis-ci.com/saltstack-formulas/php-formula/jobs/230937906#L234

My method is working but that Ubuntu job takes forever!

* https://travis-ci.org/myii/php-formula/builds/580861711

**Comment by n-rodriguez** [comment]
> My method is working but that Ubuntu job takes forever!

it's due to poor bandwitch on launchpad :/

**Comment by myii** [comment]
@n-rodriguez How do you feel about the method, so that we can keep `yamllint` functioning as it's supposed to?  It only adds the differences between the `debian` and `ubuntu` pillars.  Shall I add the commit here?

**Comment by myii** [comment]
Ignore the `yaml_dump` commit, that was just for confirming that the test pillars are still be rendered as required.  It appears to work fine:

```diff
--- .../php-formula/.kitchen/yaml_dump/Debian-9-2019.2.0-n/a-705e8cc-py3.yaml
+++ .../php-formula/.kitchen/yaml_dump/Ubuntu-18.04-2019.2.0-py3.yaml
@@ -377,10 +375,11 @@
        - xml
        - zip
        repo:
-         humanname: php-sury repo
+         humanname: php-sury ppa
-         name: deb https://packages.sury.org/php/ stretch main
+         name: deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main
          file: /etc/apt/sources.list.d/php-sury.list
-         key_url: https://packages.sury.org/php/apt.gpg
+         key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c
+       use_external_repo: true
        version:
        - '5.6'
        - '7.3'
```

**Comment by myii** [comment]
Closes #174.

**Comment by n-rodriguez** [comment]
> @n-rodriguez How do you feel about the method, so that we can keep `yamllint` functioning as it's supposed to? It only adds the differences between the `debian` and `ubuntu` pillars. Shall I add the commit here?

LGTM. feel free to add commit ;)

**Comment by myii** [comment]
@n-rodriguez OK, I've added the commit, let me know if you're happy with it.

**Comment by n-rodriguez** [comment]
> @n-rodriguez OK, I've added the commit, let me know if you're happy with it.

LGTM

**Comment by myii** [comment]
Merged, thanks @n-rodriguez.

**Pull request merged**
