### PR TITLE
Add enablerepo option to php-salt-formula

### PR DESCRIPTION
**Pull request by pawelrosada**

### CODE REVIEW

**Comment by aboe76** [comment]
@pawelrosada can you add your parameter to pillar.example so it's documented

**Comment by pawelrosada** [comment]
@aboe76 done

**Comment by aboe76** [comment]
@pawelrosada thanks for this

**Comment by sticky-note** [comment]
Need default value in map.jinja ? As this PR breaks Backward compatibility

**Comment by pawelrosada** [comment]
@sticky-note 
`  {% set enable_php_repo = salt['pillar.get']('php:ng:lookup:enable_php_repo', False) %} `

Variable is initialized in default (false). With version of SaltStack do you use?

**Comment by sticky-note** [comment]
The var is initialized in the elif statement for RedHat only: https://github.com/saltstack-formulas/php-formula/blob/0c923245e67c31bd51b78595bae57ad066c2a31b/php/ng/installed.jinja#L75and is ALWAYS read (-> outside if elsif else ).
That's because it is never initialized for Debian or other other OSes but RedHat.

**Pull request merged**
